### ISSUE TITLE
Not creating the project if not existing

### ISSUE THREAD

**Issue by Whisper40** [pmckeown/dependency-track-maven-plugin#133]
Hello, i tested your tool like that : 
```
mvn io.github.pmckeown:dependency-track-maven-plugin:${MAVEN_PLUGIN_UPLOAD_BOM_VERSION}:upload-bom -Ddependency-track.projectName=${application} -Ddependency-track.projectVersion=${CI_COMMIT_REF_NAME} -Ddependency-track.dependencyTrackBaseUrl="${BASE_URL_DEPENDENCYTRACK_UPLOAD_BOM}/bom" -Ddependency-track.apiKey=${DEPENDENCYTRACK_API_KEY} -Ddependency-track.waitUntilBomProcessingComplete=false
```

It has permissions to do what it needs, but if the project is new it won't be created by your tool 

Logs
```
[INFO] --- dependency-track-maven-plugin:0.8.8:upload-bom (default-cli) @ demo-svc-service ---
[INFO] Project Name: app-demo-svc-service
[INFO] Project Version: latest
[INFO] Plugin is configured to wait for BOM processing to complete
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.634 s
[INFO] Finished at: 2020-12-09T17:49:57Z
[INFO] ------------------------------------------------------------------------
```

In the app, the project is not created.
Before your tool we were using curl with something like that  : 
The autocreate to true in order to create the project if needed
```
echo "{\"autoCreate\": true, \"projectName\": \"$application\", \"projectVersion\": \"$CI_COMMIT_REF_NAME\", \"bom\": \"$(base64 -w 0 target/bom.xml
```

Thanks for any update for that ;)

**Comment by pmckeown** [comment]
Hi, this line in the plugin that creates the request to upload the BOM has the autoCreate flag hardcoded to true.  I couldn't think of a reason to make that configurable.
```
            Response<UploadBomResponse> response = bomClient.uploadBom(new UploadBomRequest(                    
                   commonConfig.getProjectName(), commonConfig.getProjectVersion(), true, encodedBom));
```
See 
https://github.com/pmckeown/dependency-track-maven-plugin/blob/2bff4cea563eee75de4a3b7240d5aac343c4df4a/src/main/java/io/github/pmckeown/dependencytrack/upload/UploadBomAction.java#L80

I suspect its because you have `/bom` appended to the end of the base URL property.  From your example: `${BASE_URL_DEPENDENCYTRACK_UPLOAD_BOM}/bom`

Try changing that to `${BASE_URL_DEPENDENCYTRACK_UPLOAD_BOM}` where `BASE_URL_DEPENDENCYTRACK_UPLOAD_BOM` is something like: `http://localhost:8080`

There is a property you can use to configure the plugin behaviour which I recommend you set to true while setting up your integration.  Set `-Ddependency-track.failOnError=true` to ensure that the plugin reports errors when failing to integrate.  I default this to false to ensure builds are unaffected when dependency track is unavailable but its up to you if you want to change that..

Please close this issue if this fixes it for you.

**Comment by Whisper40** [comment]
Yes you are right, i have append "api/v1/bom" :) 
Working properly with the good URL.

I have this option : -Ddependency-track.waitUntilBomProcessingComplete=false
So i don't want to have the result at the end of the upload, can you say me why i'm having this ?

```
[INFO] Plugin is configured to wait for BOM processing to complete
[INFO] BOM uploaded to Dependency Track server
[INFO] Checking for BOM analysis completion
[INFO] Still processing: true
[INFO] Still processing: true
[INFO] Still processing: true
....
....
[ERROR] Polling for processing completion was interrupted so continuing: Call 'io.github.pmckeown.dependencytrack.upload.UploadBomAction$$Lambda$107/0x0000000800365c40@4b515eab' failed after 20 tries!
[INFO] Requesting Metrics analysis for project: projectname
[INFO] Refreshing Metrics for project: projectname
```

Thanks

**Comment by pmckeown** [comment]
Hi, my bad but the README is out of date.  That property got removed when I refactored the polling to be a bit smarter.  the pollingConfig ended up as a complex object which means that you can't disable it on the command line with properties.

I suggest that you define the plugin as a dependency in your POM.  That way you can set the configuration needed to run it once and you can then use a much simpler command in your terminal.

Add the following to your POM:
```
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>io.github.pmckeown</groupId>
                    <artifactId>dependency-track-maven-plugin</artifactId>
                    <version>0.8.8</version>
                    <configuration>
                        <!--suppress UnresolvedMavenProperty -->
                        <dependencyTrackBaseUrl>${env.DEPENDENCY_TRACK_BASE_URL}</dependencyTrackBaseUrl>
                        <!--suppress UnresolvedMavenProperty -->
                        <apiKey>${env.DEPENDENCY_TRACK_API_KEY}</apiKey>
                        <failOnError>true</failOnError>
                        <pollingConfig>
                            <enabled>false</enabled>
                        </pollingConfig>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
```

Then you can just run 
```
mvn dependency-track:upload-bom  -Ddependency-track.projectName=${application} -Ddependency-track.projectVersion=${CI_COMMIT_REF_NAME}
```

I will raise an issue to update the documentation to address this.

**Comment by Whisper40** [comment]
Thanks for the response, in my case, i need to use only argument, without modifying the pom.xml. I went on another plugin that have an option for my goal. Thanks for your work !
