### ISSUE TITLE
com.google.inject.CreationException: Unable to create injector, see the following errors

### ISSUE THREAD

**Issue by jfiolek** [pmckeown/dependency-track-maven-plugin#139]
Trying to use the 0.8.8 version of the maven plugin... I get the following error:

[WARNING] ClassRealm[plugin>io.github.pmckeown:dependency-track-maven-plugin:0.8.8, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc]
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for io.github.pmckeown.dependencytrack.finding.FindingsPrinter annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit was bound.
  Did you mean?
    io.github.pmckeown.dependencytrack.finding.FindingsPrinter bound  at org.eclipse.sisu.wire.LocatorWiring

  at org.eclipse.sisu.wire.LocatorWiring

2) No implementation for io.github.pmckeown.dependencytrack.score.ScoreAction annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit was bound.
  Did you mean?
    io.github.pmckeown.dependencytrack.score.ScoreAction bound  at org.eclipse.sisu.wire.LocatorWiring

  at org.eclipse.sisu.wire.LocatorWiring

2 errors

**Comment by pmckeown** [comment]
I suspect that you are using an older version of maven. Off the top of my
head you need to use 3.6.0 or 3.6.3.

Try upgrading that. If that doesn't work, please post the following :

The mvn command you use, the Java and maven versions and an example pom.xml.

Paul
