### ISSUE TITLE
Plugin should not require a Maven project for execution

### ISSUE THREAD

**Issue by obfischer** [pmckeown/dependency-track-maven-plugin#207]
**As** user of the Dependency Track Plugin for Maven,
**I** would like to be able to use the plugin even in a project without Maven project (`pom.xml` does not exist),
**so** that I can use it to upload SBOMs to Dependency Track for projects with any technology stack.

**Comment by pmckeown** [comment]
This project is specifically a Maven plugin.  There are alternative integrations available for other workflows.  Refactoring this project to allow for non-Maven execution would be a significant piece of work and I'm not convinced the value is there.  

Therefore closing.
