### ISSUE TITLE
Findings Goal CMD Parameter

### ISSUE THREAD

**Issue by claudioandreantonio** [pmckeown/dependency-track-maven-plugin#278]
Hi there.

I reviewed the source code of the plugin and it doesn't seem to be possible to override via parameters in the command line the findings thresholds for each severity but wanted to confirm if the only way is via plugin configuration in a mvn xml config.

Thank you.

**Comment by pmckeown** [comment]
Hi, unfortunately maven doesn't allow the setting of nested or complex properties on the command line.

e.g.
```
-Ddependency-track.findingThresholds.critical
```

So yes you have to use XML config to set the thresholds.
