### ISSUE TITLE
FindingsPrinter crash when a sanitised CVE description shrinks by one chunk

### ISSUE THREAD

**Issue by pw-code** [pmckeown/dependency-track-maven-plugin#281]
The findings goal prints the details of any found CVE's, after first sanitising their content.
However if the sanitised content shrinks enough to reduce the output by one line (chunk) then the plugin crashes due to a StringIndexOutOfBoundsException.

The issue is that FindingsPrinter line 64 checks the original string length, not the cleaned string.

**Comment by pmckeown** [comment]
@pw-code - Fix released in v1.1.3.  Thanks for your contribution.
