### ISSUE TITLE
dependency-track v4.5.0 Permissions does not match to documentation

### ISSUE THREAD

**Issue by nkutsche** [pmckeown/dependency-track-maven-plugin#298]
Hi,

just played around with a new dependency-track server and this plugin and had problems with the goal `findings`.
In the documentation it say's the [required team permissions](https://github.com/pmckeown/dependency-track-maven-plugin#dependency-track-configuration) are:

> * BOM_UPLOAD
> * PORTFOLIO_MANAGEMENT
> * PROJECT_CREATION_UPLOAD
> * SCAN_UPLOAD
> * VIEW_PORTFOLIO
> * VULNERABILITY_ANALYSIS

At least in v4.5 the dependency-track does not know a permission SCAN_UPLOAD anymore. To run the goal `findings` successful I had to grant the permission VIEW_VULNERABILITY instead.

An documentation update would he helpful here.

BR, Nico

**Comment by pmckeown** [comment]
Looks like SCAN_UPLOAD was never actually needed.  I'll update the documented permissions.

**Comment by pmckeown** [comment]
Docco updated.  Thanks for the heads up.
