### ISSUE TITLE
Update use of deprecated Assert.assertThat

### ISSUE THREAD

**Issue by pmckeown** [pmckeown/dependency-track-maven-plugin#301]
There are a lot of deprecation warnings in the `src/test` about use of the method Assert.assertThat.

Please update these tests to remove the deprecation warnings without impacting the test logic.

**Comment by derlin** [comment]
Hello there ! I am taking this one :)

**Comment by derlin** [comment]
May I kindly ask you to put the label [hacktoberfest-accepted](https://hacktoberfest.com/participation/#pr-mr-details) to the PR ?
You may refuse of course, I am glad to contribute anyway :)

**Comment by pmckeown** [comment]
> Hello there ! I am taking this one :)

Thank you!

**Comment by pmckeown** [comment]
Fixed #311
