### ISSUE TITLE
Update project identity after BOM upload

### ISSUE THREAD

**Issue by elmuerte** [pmckeown/dependency-track-maven-plugin#318]
When uploading a BOM Dependency Track does not fill in the project identity fields (e.g. group, PURL). 
It looks like Dependency Track cannot update the project details based on the BOM: https://github.com/DependencyTrack/dependency-track/discussions/1156#discussioncomment-1220078

It would be nice if the plugin would use the `/v1/project` API to update the project with information from the metadata/component section in the BOM it just uploaded.

**Comment by elmuerte** [comment]
I started on a branch to implement this feature: https://github.com/elmuerte/dependency-track-maven-plugin/tree/update-project-info

**Comment by pmckeown** [comment]
Hey, what version of Dependency Track does this affect?  I assume all versions?

**Comment by elmuerte** [comment]
The project info not being filling based on SBOM data? I don't think I've ever seen this working in 3.x or 4.x.

**Comment by pmckeown** [comment]
This has been shipped in v1.3.0.  Please let me know if any issues.  Thanks for the contribution!
