### ISSUE TITLE
Add ability to set project parent on BOM upload

### ISSUE THREAD

**Issue by roadSurfer** [pmckeown/dependency-track-maven-plugin#338]
DependencyTrack supports a basci parent/child relationship between projects. I would be good if the plugin could set that value during upload, perhaps defaulting to the POM `project.parent` by some means.

**Comment by pmckeown** [comment]
This is worth thinking about.  I've never used that feature.  Is there a tangible benefit to linking these things in Dependency Track via this plugin?

**Comment by roadSurfer** [comment]
It is brand new in 4.7.0 and looking at the [logged issues](https://github.com/DependencyTrack/dependency-track/issues?q=is%3Aissue+is%3Aopen+parent, it seems it will be getting extended. For example, project "[collections](https://github.com/DependencyTrack/dependency-track/issues/2041)"
I also thought that policy violations/vulnerabilities got collated in with the parent, but I have not see it working yet (or maybe I misunderstood).

There's obviously other ways this could be done but the as plugin is uploading the BOM, potentially creating the project, optionally adding project info; why not just set the parent too? :smile: 

I actually started a new branch in my fork to add this feature (not pushed it yet) but am having some problems with the `UploadBomMojoIntegrationTest` as I haven't yet managed to create an `UploadBomResponse` via WireMock (tooling I am unfamiliar with). So it tries to work and, well, doesn't.

**Comment by roadSurfer** [comment]
Fixed my unit test issues.

So this has turned out to be rather annoying. It _looked like_ it could be done via a `patch` based on the DT OpenAPI docs (so it could possibly have been done along with the `UpdateProjectInfo` mechanism) but it turns out that this isn't implemented server-side and can only be done through `post`, which means pulling a lot more project info and then sending it back with the minor change.

This is being addressed via [DT 2401](https://github.com/DependencyTrack/dependency-track/issues/2401) but would only be possible with whichever version it is merged in to.

**Comment by pmckeown** [comment]
OK, sounds like we shouldn't follow this up until [DT 2401](https://github.com/DependencyTrack/dependency-track/issues/2401) is released.

**Comment by pmckeown** [comment]
Fixed in #346
