### ISSUE TITLE
Add ability to set project PURL during upload

### ISSUE THREAD

**Issue by roadSurfer** [pmckeown/dependency-track-maven-plugin#339]
The Package URL is one way to uniquely identify a package within DT. This information can either be derived from the POM itself (or read from the BOM xml/json). Example partial JSON BOM:
```
{
  "bomFormat" : "CycloneDX",
  "specVersion" : "1.4",
  "serialNumber" : "urn:uuid:...",
  "version" : 1,
  "metadata" : {
    "timestamp" : "2023-01-05T10:16:04Z",
    "tools" : [
      {
        "vendor" : "OWASP Foundation",
        "name" : "CycloneDX Maven plugin",
        "version" : "2.7.1",
        ...
      }
    ],
    "component" : {
      "group" : "tld.domain.foo",
      "name" : "bar",
      "version" : "1.0.0-SNAPSHOT",
      "description" : "Foo bar",
      "purl" : "pkg:maven/tld.domain.foo/bar@1.0.0-SNAPSHOT?type=jar",
      ...
```
The plugin could use a default value like "pkg:maven/${project.group}/${project.name}@${project.version}?type=${project.packaging}` or read it from the BOM.
(Note: Reading from the BOM would basically negate most of the other configuration options.)

**Comment by roadSurfer** [comment]
Checking in [BomParser](https://github.com/pmckeown/dependency-track-maven-plugin/blob/main/src/main/java/io/github/pmckeown/dependencytrack/bom/BomParser.java) it looks like this (and other information such as `group`) should be getting picked up, but they are not populated in the DT UI.
Maybe a bug?
Will have to do some digging.

**Comment by roadSurfer** [comment]
Figured it out. The namespace/PURL/CPE details are **only** set if `updateProjectInfo` is `true`.

Perhaps the docs need a minor update to state this behaviour?

**Comment by pmckeown** [comment]
Hi @roadSurfer, that was added only recently by another user.  It is documented under the UploadBom goal docs in the readme.

https://github.com/pmckeown/dependency-track-maven-plugin#configuration

Feel free to improve the docs if you think this could be more obvious.

**Comment by roadSurfer** [comment]
Closed by merge of https://github.com/pmckeown/dependency-track-maven-plugin/pull/343
