### ISSUE TITLE
Support Maven 3.9.x

### ISSUE THREAD

**Issue by MPriess** [pmckeown/dependency-track-maven-plugin#349]
We tested the dependency-track-maven-plugin 1.4.0 today with Maven 3.9.0 and it seems like that the 1.4.0 version is not compatible with Maven 3.9.0. When running the plugin, we get the following error message:

**A required class was missing while executing io.github.pmckeown:dependency-track-maven-plugin:1.4.0:upload-bom: org/codehaus/plexus/util/IOUtil**

In the release notes of Maven 3.9.0 there is the following note:

Maven 2.x was auto-injecting an ancient version of plexus-utils dependency into the plugin classpath, and Maven 3.x continued doing this to preserve backward compatibility. Starting with Maven 3.9, it does not happen anymore. This change may lead to plugin breakage. 

- The fix for affected plugin maintainers is to explicitly declare a dependency on plexus-utils. 

- The workaround for affected plugin users is to add this dependency to plugin dependencies until issue is fixed by the affected plugin maintainer. See [MNG-6965](https://issues.apache.org/jira/browse/MNG-6965).

**Comment by pmckeownkiwibank** [comment]
Thanks for reporting, will try to take a look at this over the weekend.  Feel free to submit a Pull Request if you need it sooner.

**Comment by MPriess** [comment]
Before introducing a implicit dependency to plexus-utils using Apache Commons could also be an option, which is already present in the project: https://github.com/pmckeown/dependency-track-maven-plugin/pull/350

What do you think?

**Comment by pmckeown** [comment]
Hi, version 1.4.1 has been released with this change in it.  Let me know if OK to close this issue.

Thanks!

**Comment by szpak** [comment]
@pmckeown I've just checked 1.4.1 with Maven 3.9.0 and it worked fine. Thanks!

**Comment by pmckeown** [comment]
Thanks @szpak !

**Comment by MPriess** [comment]
Tested the release today with my colleague and we can confirm that the error no longer occurs.
