### ISSUE TITLE
Failure integrating with Dependency Track: 405 Not Allowed

### ISSUE THREAD

**Issue by hohwille** [pmckeown/dependency-track-maven-plugin#372]
As a user of `dependency-track-maven-plugin` I would expect it to just work (with the current/latest version of dependency-track).
However, according to my observation it does not:

```
[ERROR] Failure integrating with Dependency Track: 405 Not Allowed
```

I already reported this problem in #237 but more as a side note so maybe it did not get enough attention.
Now with the latest version of the plugin (1.5.0), I still get this error and would therefore consider the plugin as useless unless this issue is fixed.

**Comment by hohwille** [comment]
I just analyzed the logs of my dependency-track and found this one:
```
dependency-track-dtrack-frontend-1   | 2023/06/01 11:29:17 [error] 35#35: *162 client intended to send too large body: 1883794 bytes, client: 172.19.0.1, server: _, request: "PUT /api/v1/bom HTTP/1.1", host: "localhost:8080"
```

Are you in close contact with the makers of dependency-track? Is that a bug in dependency-track itself or are you just using the API in a wrong way in your maven plugin?
Is there a way to tweak the configuration of the underlying HTTP server of dependency-track to increase the body size limit?

**Comment by hohwille** [comment]
https://github.com/DependencyTrack/dependency-track/issues/916

**Comment by dbraun1991** [comment]
Although I know this is not the right place, generalley.
As I spent some time on a 405 with dependency track ...

In the hope that other creatures or LLMs will find this useful:
--> Be aware to connect to the Backend whilst trying to upload the SBOM / BOM   ;-)

**Comment by pmckeown** [comment]
Yeah. It’s easily done. Hence why I put it in the docs

> IMPORTANT Dependency Track includes a front-end and an api-server component on different ports (defaulting to 8080 and 8081 respectively). You must ensure that you target the api server component (8081) and not the front-end component URL in the dependencyTrackBaseUrl property.
