### ISSUE TITLE
Finding Mojo not callable from CLI with Parameters

### ISSUE THREAD

**Issue by thomasrepnik** [pmckeown/dependency-track-maven-plugin#380]
The Finding Mojo has no properties defined to call the Goal from CLI. 

Would be great if this would possible:

`mvn io.github.pmckeown:dependency-track-maven-plugin:1.5.0:findings -DfindingThresholds.critical=5 -Ddependency-track.dependencyTrackBaseUrl=YYYY -Ddependency-track.apiKey=XXXX`

**Comment by pmckeown** [comment]
This has been released in version 1.6.0.  Please try it out and report/fix any issues if you find any. Thanks!
