### ISSUE TITLE
Unable to list projects 

### ISSUE THREAD

**Issue by venkateshzifo** [pmckeown/dependency-track-maven-plugin#394]
Unable to list project when I run maven command 

Command:
mvn io.github.pmckeown:dependency-track-maven-plugin:findings

pom file properties 

```
<dependencyTrackBaseUrl>{url}</dependencyTrackBaseUrl>
<apiKey>{key}</apiKey>
<projectName>{name}</projectName>
<projectVersion>1.0</projectVersion>
<failOnError>true</failOnError>
<verifySsl>false</verifySsl>
```

Permissions given 
using default admin user API key

Error: 
Getting error Failed to list projects

Please help me with this issue

**Comment by pmckeown** [comment]
Hi, is this still an issue for you?  Can you please provide more info?  Ideally, execute the same command with the `-X` option and post the log (though do check it first for any sensitive info like your API Key)
