### ISSUE TITLE
Unable to load the mojo 'upload-bom'

### ISSUE THREAD

**Issue by wklenk** [pmckeown/dependency-track-maven-plugin#70]
Ubuntu 18, Apache Maven 3.6.0

In the shell, I enter the following command:

`$ mvn dependency-track:upload-bom`

I get the following error messages:

```
[WARNING] ClassRealm[plugin>io.github.pmckeown:dependency-track-maven-plugin:0.8.0, parent: sun.misc.Launcher$AppClassLoader@1b6d3586]
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for io.github.pmckeown.dependencytrack.score.ScoreAction annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit was bound.
  at org.eclipse.sisu.wire.LocatorWiring

2) No implementation for io.github.pmckeown.dependencytrack.upload.UploadBomAction annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit was bound.
  at org.eclipse.sisu.wire.LocatorWiring

3) No implementation for io.github.pmckeown.dependencytrack.finding.report.XmlReportWriter annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit was bound.
  at org.eclipse.sisu.wire.LocatorWiring

4) No implementation for io.github.pmckeown.dependencytrack.finding.FindingsPrinter annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit was bound.
  at org.eclipse.sisu.wire.LocatorWiring

5) No implementation for io.github.pmckeown.dependencytrack.metrics.MetricsAction annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit was bound.
  at org.eclipse.sisu.wire.LocatorWiring

5 errors
    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist (Errors.java:466)
    at com.google.inject.internal.InternalInjectorCreator.initializeStatically (InternalInjectorCreator.java:155)
    at com.google.inject.internal.InternalInjectorCreator.build (InternalInjectorCreator.java:107)
    at com.google.inject.Guice.createInjector (Guice.java:99)
    at com.google.inject.Guice.createInjector (Guice.java:73)
    at com.google.inject.Guice.createInjector (Guice.java:62)
```
and

```
Execution default-cli of goal io.github.pmckeown:dependency-track-maven-plugin:0.8.0:upload-bom failed: Unable to load the mojo 'upload-bom' (or one of its required components) from the plugin 'io.github.pmckeown:dependency-track-maven-plugin:0.8.0': java.util.NoSuchElementException
[ERROR]       role: org.apache.maven.plugin.Mojo
[ERROR]   roleHint: io.github.pmckeown:dependency-track-maven-plugin:0.8.0:upload-bom
[ERROR] -> [Help 1]
```
For me it seems that there is something corrupt with the dependency injection of the Mojos. Do I need to add some dependencies to my pom.xml ? What's wrong?

**Comment by pmckeown** [comment]
Sorry for the delay - I've just seen this and github didn't email me about it!

I would firstly recommend that you use the latest version 0.8.1 though I doubt that will fix the issue. 

Secondly, do you have a OSS repo that exhibits this behaviour so I can try to reproduce it or can you include your pom.xml in a comment?

FYI I develop on OSX with Maven version 3.6.1.

**Comment by gfrancqu** [comment]
same issue there, using maven 3.6.3

**Comment by michalbartnicki** [comment]
Hey, is there any progress on this issue?
I got the same result on mvn 3.6.0 @ Elementary 5.1.

**Comment by pmckeown** [comment]
I am unable to reproduce this issue.  Could you please run the target with the `-X` maven parameter and attach the output?

**Comment by JHAServiceTrace** [comment]
Hi,
I have the same issue. For testing purposes I created a small maven project and tried to upload a  CycloneDX BOM to our Dependency-Track server. To create the BOM I used the org.cyclonedx:cyclonedx-maven-plugin:1.6.4 plugin. To upload the BOM I used your plugin in version 0.8.1.

The call of "mvn dependency-track:upload-bom -X" produces the following output:

[dependency-track-error.txt](https://github.com/pmckeown/dependency-track-maven-plugin/files/4328565/dependency-track-error.txt)


Regards

   Jochen

**Comment by pmckeown** [comment]
Thanks Jochen, the main difference I could see in that verbose output (aside from the OS) was Java version.  I updating to the following and it still works fine for me.

`Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.6, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_NZ, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"
` 

Is there anything else different about your configuration?  I doubt the minor version differences in Maven and Java 11 will be significant.  

I wonder if there is anything else in the classpath which could be interfering with the dependency injection framework?

**Comment by JHAServiceTrace** [comment]
Hi Paul,

please excuse the late reply. I have updated Maven to 3.6.3 and it works. I also had doubts, if the Maven version is the problem, but I wanted to give the newest version a try. Perfect.

Thanks for your help.

Regards
    Jochen

**Comment by pmckeown** [comment]
Great to hear, thanks for reporting back.  I'll mark this issue as closed.  

Resolution is upgrade to the latest Maven release v3.6.3

https://maven.apache.org/download.cgi
