### ISSUE TITLE
Unable to load the mojo 'upload-bom' (or one of its required components) from the plugin 'io.github.pmckeown:dependency-track-maven-plugin

### ISSUE THREAD

**Issue by asayar666** [pmckeown/dependency-track-maven-plugin#75]
Hi,

i am facing the same issuer as another member described in April (the issue is marked as fixed) on my CI/CI (jenkins) machine:

I am using the described "as working" version of Maven (3.6.3). The issue appears with OpenJDK 11 as well as with OpenJDK 14.

Error description:
Execution default-cli of goal io.github.pmckeown:dependency-track-maven-plugin:0.8.2:help failed: Unable to load the mojo 'upload-bom' (or one of its required components) from the plugin 'io.github.pmckeown:dependency-track-maven-plugin

Looking deeper into the stack trace shows the following:
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.apache.maven.plugin.Mojo
  roleHint: io.github.pmckeown:dependency-track-maven-plugin:0.8.2:upload-bom

The error is the same for all goals for this plugin.

**Comment by asayar666** [comment]
I could fix the issue:
reason was the Ubuntu 20 provided Maven 3.6.3. Removed the provided maven package and manually installed 3.6.3 version

**Comment by pmckeown** [comment]
Thanks asayar66.

Sounds like the fix was reinstalling the same version of Maven 3.6.3?  Weird - I wonder if the Ubuntu provided one has some slightly different behaviour or configuration?

Marking this as closed as you have resolved it.  Thanks for posting your fix.
