### ISSUE TITLE
Create Project In Dependecy Track when it doesn't Exist

### ISSUE THREAD

**Issue by rylyade1** [pmckeown/dependency-track-maven-plugin#76]
Currently it is not possible to upload a project's BOM to dependency track, if that project doesn't exist already. 
In order to avoid the overhead of manually creating the project in dependency track, this plugin could automatically create a project and then upload the BOM.

An argument (e.g. **autoCreate**) could be added to enable this.

**Comment by pmckeown** [comment]
Hi rylyade, that is the default behaviour at this time.  The flag set in the BomUploadRequest is hardcoded to `true`:

https://github.com/pmckeown/dependency-track-maven-plugin/blob/master/src/main/java/io/github/pmckeown/dependencytrack/upload/UploadBomAction.java#L80-L81

Paul

**Comment by pmckeown** [comment]
For further info, this is the description from the D Track API that I am using to upload the BOM:
```
Expects CycloneDX or SPDX (text or RDF) along and a valid project UUID. If a UUID is not specified, than the projectName and projectVersion must be specified. Optionally, if autoCreate is specified and 'true' and the project does not exist, the project will be created. In this scenario, the principal making the request will additionally need the PORTFOLIO_MANAGEMENT or PROJECT_CREATION_UPLOAD permission.
```

**Comment by rylyade1** [comment]
Hi @pmckeown ,

thank you for the clarification.
